"""Build the static pages with shared navigation, service data and contact UI."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'tools/services.json'
services = json.loads(DATA.read_text())
EMAIL = 'ambiental.cya@gmail.com'
WA = 'https://wa.me/593988125641'
icons = {
 'leaf':'<path d="M20 3C9 2 3 8 5 15c2 7 12 6 15-12Z"/><path d="M3 22 15 10"/>',
 'mountain':'<path d="m1 21 9-17 5 9 3-5 5 13ZM7 10l3 3 3-3"/>',
 'document':'<path d="M5 2h10l4 4v16H5ZM15 2v5h4M8 11h8M8 15h8M8 19h5"/>',
 'group':'<circle cx="12" cy="5" r="3"/><circle cx="4" cy="8" r="2"/><circle cx="20" cy="8" r="2"/><path d="M7 21v-5a5 5 0 0 1 10 0v5ZM2 20v-5a3 3 0 0 1 4-3M22 20v-5a3 3 0 0 0-4-3"/>',
 'gear':'<path d="m10 2 4 0 1 3 3-1 2 3-1 3 3 1v3l-3 1 1 3-3 2-3-1-1 3h-3l-1-3-3 1-2-3 1-3-3-1v-3l3-1-1-3 3-2 3 1Z"/><circle cx="12" cy="12" r="4"/>',
 'crane':'<path d="M3 22V5h18L3 2v3M3 5l8-3M3 5l8 5M11 2v20M3 22h11M11 10H2M20 5v9h-3M2 12l9 5-8 5"/>',
 'chart':'<path d="M2 22h21M5 21V12h4v9M11 21V7h4v14M17 21V2h4v19"/>',
 'mail':'<rect x="2" y="4" width="20" height="16" rx="1"/><path d="m2 5 10 9L22 5"/>',
 'phone':'<path d="M6 3H3c-2 8 10 20 18 18v-4l-5-2-2 3c-4-2-6-4-8-8l3-2Z"/>',
 'pin':'<path d="M12 22S4 14 4 9a8 8 0 1 1 16 0c0 5-8 13-8 13Z"/><circle cx="12" cy="9" r="3"/>'
}
def icon(name):
 return '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[name]+'</svg>'
def arrow(): return '<span aria-hidden="true">→</span>'
def url(prefix, sid): return prefix+'servicios/'+sid+'/'
def header(prefix='',current='home'):
 home=prefix+'index.html'
 links=[('Servicios',prefix+'servicios/'),('Sectores',home+'#sectores'),('Capacitaciones',url(prefix,'capacitaciones')),('La firma',home+'#firma'),('Contacto','#contacto')]
 return f'''<a class="skip" href="#contenido">Saltar al contenido</a><header class="site-header"><div class="header-inner"><a class="brand" href="{home}" aria-label="Clavijo y Asociados, inicio"><svg class="brand-logo" viewBox="80 20 440 365" aria-hidden="true"><image href="{prefix}assets/images/logo.webp" width="600" height="510"/></svg><span><strong>CLAVIJO Y ASOCIADOS</strong><small>Desarrollo con Conciencia</small></span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation" aria-label="Abrir menú"><span></span><span></span><span></span></button><nav id="navigation" aria-label="Navegación principal">{''.join(f'<a href="{h}"'+(' aria-current="page"' if (current=='services' and t=='Servicios') or (current=='capacitaciones' and t=='Capacitaciones') else '')+f'>{t}</a>' for t,h in links)}<a class="button gold" href="#contacto">Solicitar evaluación {arrow()}</a></nav></div></header>'''
def footer(prefix=''):
 return f'''<footer class="site-footer"><div class="footer-inner"><a class="brand" href="{prefix}index.html"><svg class="brand-logo" viewBox="80 20 440 365" aria-hidden="true"><image href="{prefix}assets/images/logo.webp" width="600" height="510"/></svg><span><strong>CLAVIJO Y ASOCIADOS</strong><small>Desarrollo con Conciencia</small></span></a><nav aria-label="Navegación al pie"><a href="{prefix}servicios/">Servicios</a><a href="{prefix}index.html#sectores">Sectores</a><a href="{url(prefix,'capacitaciones')}">Capacitaciones</a><a href="{prefix}index.html#firma">La firma</a><a href="#contacto">Contacto</a></nav><p>Quito, Ecuador</p></div></footer>'''
def contact(prefix='',selected=''):
 options=''.join(f'<option'+(' selected' if s[0]==selected else '')+'>'+escape(s[1])+'</option>' for s in services)
 return f'''<section class="contact" id="contacto"><div class="contact-grid container"><div class="contact-heading reveal"><p class="eyebrow">Contáctanos</p><h2>Cuéntanos qué<br>necesitas resolver.</h2></div><div class="contact-data reveal"><p>{icon('mail')}<a href="mailto:{EMAIL}">{EMAIL}</a></p><p>{icon('phone')}<a href="{WA}" target="_blank" rel="noopener noreferrer">+593 98 812 5641</a></p><p>{icon('pin')}<span>Quito, Ecuador</span></p></div><form id="contact-form" class="contact-form reveal"><div class="form-fields"><div class="form-row"><div><label for="nombre">Nombre *</label><input id="nombre" name="nombre" autocomplete="name" placeholder="Nombre" required maxlength="100"></div><div><label for="empresa">Empresa</label><input id="empresa" name="empresa" autocomplete="organization" placeholder="Empresa" maxlength="150"></div></div><div class="form-row"><div><label for="email">Correo *</label><input id="email" name="email" type="email" autocomplete="email" placeholder="Correo" required maxlength="150"></div><div><label for="servicio">Servicio de interés *</label><select id="servicio" name="servicio" required><option value="">Servicio de interés</option>{options}<option>Necesito orientación</option></select></div></div><label for="mensaje">Mensaje *</label><textarea id="mensaje" name="mensaje" placeholder="Mensaje" rows="3" required minlength="10" maxlength="2000"></textarea></div><div class="form-actions"><button type="submit" class="button gold" disabled aria-describedby="form-explanation">Enviar mensaje {arrow()}</button><a class="whatsapp-link" href="{WA}" target="_blank" rel="noopener noreferrer">O conversemos por WhatsApp {arrow()}</a></div><p class="form-explanation" id="form-explanation">Se abrirá tu aplicación de correo para revisar y enviar la consulta. * Campos obligatorios.</p><p id="form-status" role="status" aria-live="polite"></p><a id="email-fallback" class="text-link" hidden>Abrir la consulta en mi aplicación de correo {arrow()}</a><noscript><p>Escríbenos directamente a <a href="mailto:{EMAIL}">{EMAIL}</a> o por WhatsApp.</p></noscript></form></div></section>'''
def document(body,title,description,prefix='',current='home'):
 schema={'@context':'https://schema.org','@type':'Organization','name':'Clavijo y Asociados','slogan':'Desarrollo con Conciencia','email':EMAIL,'telephone':'+593988125641','address':{'@type':'PostalAddress','addressLocality':'Quito','addressCountry':'EC'},'areaServed':'Ecuador'}
 return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} · Clavijo y Asociados</title><meta name="description" content="{escape(description)}"><meta name="robots" content="noindex, nofollow"><meta name="theme-color" content="#102f40"><meta property="og:title" content="{escape(title)} · Clavijo y Asociados"><meta property="og:description" content="{escape(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="es_EC"><meta property="og:image" content="{prefix}assets/images/social.jpg"><link rel="icon" href="{prefix}assets/images/favicon.png"><link rel="stylesheet" href="{prefix}assets/css/styles.css"><script src="{prefix}assets/js/main.js" defer></script><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><svg width="0" height="0" aria-hidden="true" style="position:absolute"><defs><filter id="logo-ink" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 -1 -1 -1 0 3"/></filter></defs></svg>{header(prefix,current)}<main id="contenido">{body}</main>{footer(prefix)}</body></html>'''
def photo(name,alt,prefix='',cls=''):
 return f'<img class="{cls}" src="{prefix}assets/images/{name}.webp" width="1440" height="960" loading="lazy" alt="{escape("Imagen ilustrativa. "+alt)}">'

pillars=[('leaf','Criterio técnico','Decisiones sustentadas en información, normativa y análisis especializado.'),('mountain','Visión territorial','Comprensión integral del territorio, sus dinámicas, restricciones y oportunidades.'),('document','Gestión y cumplimiento','Soluciones aplicables que permiten gestionar obligaciones, riesgos y requerimientos ambientales.'),('group','Ejecución coordinada','Dirección técnica y seguimiento durante las distintas etapas del proyecto.')]
capacity=[('field-water','Gestión ambiental<br>y cumplimiento','regularizacion','Técnico evaluando condiciones junto a un río.'),('home-territory','Ordenamiento territorial<br>y sistemas de información geográfica','sig','Vista territorial de bosque y río.'),('industrial-operation','Residuos y economía<br>circular','residuos','Infraestructura industrial junto a un cuerpo de agua.'),('natural-heritage','Patrimonio natural<br>y biodiversidad','patrimonio','Ave en un entorno de bosque.'),('field-monitoring','Monitoreo ambiental<br>e información técnica','monitoreos','Inspección de equipos de monitoreo en campo.'),('technical-training','Certificaciones,<br>programas y formación','certificaciones','Sesión técnica con cartografía en pantalla.')]
sectors=[('gear','Industria','Gestión ambiental, cumplimiento y desempeño operativo.'),('crane','Infraestructura','Evaluación, planificación y gestión de impactos.'),('chart','Actividades<br>productivas','Gestión responsable del territorio y los recursos.'),('leaf','Patrimonio natural','Conservación, manejo y planificación.'),('group','Organizaciones<br>y territorio','Gestión ambiental, planificación y fortalecimiento institucional.')]
steps=[('Diagnóstico','Comprendemos el proyecto, su contexto y sus requerimientos.'),('Alcance','Definimos actividades, metodología, entregables y planificación.'),('Desarrollo','Ejecutamos los componentes técnicos y gestionamos su seguimiento.'),('Entrega','Consolidamos resultados, productos técnicos y documentación final.')]
home=f'''<section class="hero" id="inicio"><img class="hero-background" src="assets/images/home-territory.webp" alt="" width="1920" height="1080" fetchpriority="high"><div class="container hero-content reveal"><p class="eyebrow light">Consultoría ambiental · Ecuador</p><h1>Convertimos la gestión<br class="desktop-break"> ambiental en <span>valor,<br class="desktop-break"> confianza y sostenibilidad.</span></h1><p class="hero-description">Firma consultora especializada en gestión ambiental, territorio y cumplimiento para empresas, industrias, infraestructura y proyectos de desarrollo.</p><div class="hero-actions"><a class="button gold" href="#contacto">Solicitar evaluación {arrow()}</a><a class="hero-secondary" href="#contacto">Conversemos sobre tu proyecto {arrow()}</a></div></div><div class="hero-concepts" aria-label="Ámbitos de nuestra práctica"><span>Ambiente</span><span>Territorio</span><span>Información</span><span>Cumplimiento</span><span>Sostenibilidad</span></div></section>
<section class="firm" id="firma"><div class="firm-copy reveal"><p class="eyebrow">Quiénes somos</p><h2>Conocimiento técnico<br>para un desarrollo sostenible.</h2><p>Clavijo y Asociados es una firma consultora especializada en gestión ambiental y territorial. Integramos capacidades en cumplimiento ambiental, patrimonio natural, monitoreo, información geográfica, gestión de residuos y sostenibilidad para estructurar soluciones técnicamente sólidas y aplicables a la realidad de cada proyecto.</p></div><div class="firm-photo">{photo('firm-field','Inspección territorial con infraestructura y bosque en el entorno.')}<p class="firm-photo-note">Soluciones<br>ambientales<br>para un futuro<br>viable</p></div></section>
<section class="approach" id="enfoque"><div class="approach-heading reveal"><p class="eyebrow">Nuestro enfoque</p><h2>Cómo abordamos<br>cada proyecto.</h2><p>Integramos análisis técnico, comprensión territorial y conocimiento normativo para responder a los desafíos ambientales de cada operación y proyecto.</p></div>{''.join(f'<article class="pillar reveal">{icon(i)}<h3>{t}</h3><p>{d}</p></article>' for i,t,d in pillars)}</section>
<section class="capacity" id="servicios"><div class="capacity-heading reveal"><p class="eyebrow">Nuestra capacidad</p><h2>Capacidad<br>técnica integrada.</h2><p>Nuestra práctica integra distintas especialidades ambientales y territoriales dentro de una misma estructura de trabajo, permitiendo abordar proyectos desde el diagnóstico y la planificación hasta el desarrollo técnico y la gestión de resultados.</p><a class="text-link" href="servicios/">Conozca nuestros servicios {arrow()}</a></div><div class="capacity-grid">{''.join(f'<article class="capacity-tile reveal">{photo(n,a)}<div class="tile-overlay"><a href="{url("",sid)}">{t} {arrow()}</a>'+('<a class="tile-training-link" href="servicios/capacitaciones/">Capacitaciones especializadas →</a>' if sid=='certificaciones' else '')+'</div></article>' for n,t,sid,a in capacity)}</div></section>
<section class="sectors" id="sectores"><div class="sectors-heading reveal"><p class="eyebrow light">Una práctica aplicable</p><h2>A distintos sectores.</h2><p>Las necesidades ambientales varían según el territorio, la operación y el marco regulatorio. Nuestra metodología permite estructurar respuestas técnicas acordes con las particularidades de cada actividad y proyecto.</p></div>{''.join(f'<article class="sector reveal">{icon(i)}<h3>{t}</h3><p>{d}</p></article>' for i,t,d in sectors)}</section>
<section class="process"><div class="process-heading reveal"><p class="eyebrow">Nuestro proceso</p><h2>Del análisis a la solución.</h2><p>Aplicamos una metodología clara y flexible, que se adapta a las necesidades de cada proyecto y sector.</p></div><ol class="process-steps">{''.join(f'<li class="reveal"><div class="step-line"><span>0{i+1}</span>'+('<b aria-hidden="true">›</b>' if i<3 else '')+f'</div><h3>{t}</h3><p>{d}</p></li>' for i,(t,d) in enumerate(steps))}</ol></section>
<section class="vision" id="vision"><img class="vision-background" src="assets/images/vision-river.webp" width="1920" height="1080" loading="lazy" alt="Imagen ilustrativa de un río y bosque al atardecer."><div class="container vision-content"><div class="reveal"><p class="eyebrow light">Nuestra visión</p><h2>Desarrollo con conciencia.</h2><p>Entendemos las relaciones entre territorio, actividad productiva y patrimonio natural para construir soluciones que hagan posible un desarrollo técnicamente sustentado y ambientalmente responsable.</p><button class="button gold" type="button" data-play-video>Conozca nuestra visión {arrow()}</button></div><button class="vision-play" type="button" data-play-video aria-label="Reproducir video de nuestra visión"><span class="play-circle" aria-hidden="true">▶</span><span>Conozca nuestra firma<br>en este breve video</span></button></div><div class="vision-video" hidden><video id="landscape-video" controls muted loop playsinline preload="none" poster="assets/images/vision-river.webp" aria-label="Video institucional de Clavijo y Asociados"><source data-src="assets/video/vision-clavijo-asociados.mp4" type="video/mp4"></video><p class="video-error" hidden role="status">El video estará disponible una vez incorporado al sitio.</p><button type="button" class="close-video" aria-label="Cerrar video">Cerrar video ×</button></div><noscript><p class="video-direct">El video institucional requiere JavaScript para reproducirse.</p></noscript></section>'''
(ROOT/'index.html').write_text(document(home+contact(),'Desarrollo con Conciencia','Firma consultora especializada en gestión ambiental, territorio y cumplimiento para empresas, industrias, infraestructura y proyectos de desarrollo.'))

# The service pages keep the original offering and expanded scope in a shared system.
images={'regularizacion':'industrial-operation','patrimonio':'home-territory','residuos':'residuos','monitoreos':'monitoreos','sig':'sig','certificaciones':'industrial-operation','capacitaciones':'technical-training'}
expanded={
 'regularizacion':[('EsIA y Registros Ambientales','Términos de referencia, levantamiento de línea base, medidas ambientales y gestión documental ante las autoridades.'),('Auditorías e Informes de Cumplimiento','Revisión de obligaciones e información de respaldo para evaluar el cumplimiento ambiental.'),('Planes de Manejo Ambiental','Instrumentos de gestión con medidas, seguimiento y documentación según los requerimientos del proyecto.')],
 'patrimonio':[('BVP: declaración y planes de manejo','Inventarios y delimitaciones, documentación técnica y planificación del manejo de bosques y vegetación protectores.'),('Adjudicación de tierras en Patrimonio Forestal','Soporte ambiental y territorial para la documentación técnica del proceso, conforme al alcance acordado.'),('Estudios de biodiversidad y conservación','Análisis de biodiversidad, salvaguardas, conectividad ecológica y medidas de compensación según el proyecto.')],
 'residuos':[('Registro Generador y Declaración Anual','Documentación e información técnica para las obligaciones del generador de residuos peligrosos.'),('Planes de minimización y disposición final','Planificación de la gestión, rutas, indicadores y coordinación documental con gestores autorizados.'),('Responsabilidad extendida: RAEE, llantas y pilas','Soporte técnico para los instrumentos y obligaciones de gestión aplicables.')],
 'monitoreos':[('Aire, agua, suelo, ruido y RNI —campos electromagnéticos—','Protocolos de monitoreo, control de calidad e información técnica según los componentes y el alcance definidos.'),('Emisiones industriales','Información de monitoreo para evaluar las condiciones y obligaciones de la actividad.'),('Monitoreo de cumplimiento','Reportes y documentación técnica para sustentar decisiones y seguimiento ambiental.')],
 'sig':[('Mapas temáticos con ArcGIS Pro','Cartografía para comprender el territorio y comunicar información ambiental.'),('Levantamientos y análisis espacial','Análisis geoespacial, dashboards, story maps y reportes ejecutivos cuando el alcance los contemple.'),('Procesamiento de imágenes satelitales','Información territorial y análisis de coberturas conforme a las necesidades del proyecto.')],
 'certificaciones':[('Punto Verde (MAATE)','Información técnica y evidencias para el programa, según el alcance acordado.'),('Ecuador Carbono Cero','Inventario de gases de efecto invernadero, huella de carbono y planes de reducción.'),('GRECI / PGI','Documentación de respaldo y evidencias para los programas y auditorías aplicables.')],
 'capacitaciones':[('Gestión ambiental y residuos','Formación ajustada a las necesidades y al contexto de la organización.'),('ArcGIS (ArcMap/Pro)','Formación en herramientas de información geográfica con aplicación práctica.'),('Cambio climático y normativa','Formación para comprender y aplicar criterios climáticos y ambientales en el trabajo.')]
}
intro='''<section class="services-intro container"><p class="eyebrow">Nuestras especialidades</p><h1>Criterio técnico.<br><span>Una visión integral.</span></h1><p>Siete líneas de trabajo que conectan ambiente, territorio, información, cumplimiento y sostenibilidad.</p></section>'''
listing=''.join(f'''<article class="service-row container reveal"><div class="service-row-copy"><p class="eyebrow">0{i+1} / {escape(s[1])}</p><h2>{s[1]}</h2><p>{s[3]}</p><ul>{''.join('<li>'+escape(t)+'</li>' for t in s[4].split('; '))}</ul><div class="service-actions"><a class="text-link" href="{s[0]}/">Ver alcance {arrow()}</a><a class="button outline" href="#contacto" data-service="{s[1]}">Consultar este servicio {arrow()}</a></div></div><figure>{photo(images[s[0]],'Imagen ilustrativa de '+s[1].lower(),'../')}<figcaption>Imagen ilustrativa del servicio.</figcaption></figure></article>''' for i,s in enumerate(sorted(services,key=lambda s:['regularizacion','patrimonio','residuos','monitoreos','sig','certificaciones','capacitaciones'].index(s[0]))))
(ROOT/'servicios').mkdir(exist_ok=True)
(ROOT/'servicios/index.html').write_text(document(intro+listing+contact('../'),'Servicios ambientales','Conoce las siete especialidades de Clavijo y Asociados: regularización, patrimonio natural, residuos, monitoreos, SIG, certificaciones y capacitaciones.','../','services'))
for s in services:
 sid,title,tag,desc,bullets,scope,out,_=s
 prefix='../../'
 hero=f'''<section class="service-hero"><img src="{prefix}assets/images/{images[sid]}.webp" alt="" width="1920" height="1080" fetchpriority="high"><div class="container"><a class="breadcrumb" href="../">Servicios {arrow()}</a><p class="eyebrow light">Práctica especializada</p><h1>{title}</h1><p>{desc}</p><a class="button gold" href="#contacto">Consultar este servicio {arrow()}</a></div></section>'''
 offering=''.join(f'<article class="offering reveal"><span class="offering-number">0{i+1}</span><div><h3>{escape(t)}</h3><p>{escape(d)}</p></div></article>' for i,(t,d) in enumerate(expanded[sid]))
 related=''.join(f'<a href="../{x[0]}/">{x[1]} {arrow()}</a>' for x in services if x[0]!=sid)
 body=hero+f'''<section class="service-introduction container section reveal"><p class="eyebrow">{title}</p><h2>{tag}</h2><p class="lead">{desc}</p><p>{scope}</p>'''+('<p>Capacitaciones dirigidas a empresas, profesionales y particulares. El programa se ajusta a las necesidades de formación y aplicación práctica.</p>' if sid=='capacitaciones' else '')+f'''</section><section class="service-offerings section"><div class="container"><p class="eyebrow">Nuestra intervención</p><h2>Qué desarrollamos.</h2><div class="offering-list">{offering}</div></div></section><section class="scope-section section container"><div class="reveal"><p class="eyebrow">Alcance</p><h2>Respaldo técnico<br>para cada proyecto.</h2><p>{scope}</p><p>Las actividades, metodología, entregables y planificación se definen en la propuesta de cada proyecto.</p></div><div class="reveal"><p class="eyebrow">Entregables frecuentes</p><h2>Información aplicable.</h2><p>{out}</p><details><summary>Condiciones del alcance <span aria-hidden="true">+</span></summary><p>Los productos y actividades se acuerdan según las necesidades del proyecto. Los procedimientos de aprobación dependen de la autoridad competente y de los requisitos aplicables.</p></details></div></section><section class="service-related section"><div class="container"><p class="eyebrow">Una visión integral</p><h2>Servicios relacionados.</h2><div class="related-links">{related}</div></div></section>'''+contact(prefix,sid)
 (ROOT/'servicios'/sid).mkdir(exist_ok=True)
 (ROOT/'servicios'/sid/'index.html').write_text(document(body,title,desc,prefix,sid))
print('Built homepage, service directory and seven service pages.')
